server:
  port: 8080 

spring:
  # データソース設定
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # JPA設定
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: false
  
  # レスポンスの文字コード設定
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  
  # Redis設定
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
  
  # セッション設定
  session:
    store-type: none
    timeout: 30m

# カスタムアプリケーション設定
app:
  # APIキー（環境変数から取得）
  openai:
    api-key: ${OPENAI_API_KEY:}
  deepl:
    api-key: ${DEEPL_API_KEY:}
  
  # Auth0の設定
  auth0:
    domain: ${AUTH0_DOMAIN:}
    clientId: ${AUTH0_CLIENT_ID:}
    clientSecret: ${AUTH0_CLIENT_SECRET:}
    audience: ${AUTH0_AUDIENCE:}
    redirectUri: ${AUTH0_REDIRECT_URI:http://localhost:3000/callback}
    logoutRedirectUri: ${AUTH0_LOGOUT_REDIRECT_URI:http://localhost:3000}
  
  # セッション設定
  session:
    timeout-minutes: 30
    cleanup-interval-ms: 3600000
    cookie:
      secure: false
      http-only: true
      same-site: Lax

# Flyway設定
flyway:
  enabled: true
  locations: classpath:db/migration
  baseline-on-migrate: true

# ロギング設定
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE 